services:
  - type: web
    name: stock-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TWELVE_DATA_KEY
        sync: false
    runtime: python-3.10.13
