services:
  - type: web
    name: stock-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers=1 --threads=1 --timeout 120
    envVars:
      - key: TWELVE_DATA_KEY
        sync: false

env:
  python: 3.10.13
